# configurações de documentação da api
springdoc:
    api-docs.path: /swagger-ui/api-docs
    swagger-ui.path: /swagger-ui.html
    swagger-ui.operationsSorter: method  

spring: 
    #set max upload size to files
    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
    #configurações de acesso ao banco de dados para postgres
    datasource:
        url: jdbc:postgresql://pgsql:5432/parking_db
        username: park_api
        password: park_api_123
        driver-class-name: org.postgresql.Driver
    # configurações da ORM de acesso aos dados
    jpa:
        hibernate:
            ddl-auto: create-drop #update quando mais avançado no sistema
        show-sql: true
        open-in-view: true
        properties:
            hibernate:
                format-sql: true
        database: postgresql
    #configurações de horarios e datas
    jackson:
        date-format: "yyyy-MM-dd HH:mm:ss.SSS"
        time-zone: "GMT+8"
    
    kafka:
        producer: 
            bootstrap-servers: kafka:9092
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
        consumer:  
            bootstrap-servers: kafka:9092
            group-id: parking-group
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
            auto-offset-reset: earliest
            enable-auto-commit: false
            max-poll-records: 1
server:
    # Porta de execução do backend
    port: 8030
api:
    default-page-size: 10