# configurações de documentação da api
springdoc:
    api-docs.path: /swagger-ui/api-docs
    swagger-ui.path: /swagger-ui.html
    swagger-ui.operationsSorter: method  

spring: 
    #configurações de acesso ao banco de dados para postgres
    datasource:
        url: jdbc:postgresql://pgsql:5432/parking_db
        username: park_api
        password: park_api_123
        driver-class-name: org.postgresql.Driver
    # configurações da ORM de acesso aos dados
    jpa:
        hibernate:
            ddl-auto: create-drop #update quando mais avançado no sistema
        show-sql: true
        open-in-view: true
        properties:
            hibernate:
                format-sql: true
        database: postgresql
    #configurações de horarios e datas
    jackson:
        date-format: "yyyy-MM-dd HH:mm:ss.SSS"
        time-zone: "GMT+8"
        
server:
    # Porta de execução do backend
    port: 8030